### ISSUE TITLE
LOG模块中有不能输出string 类型，会出现乱码

### ISSUE THREAD

**Issue by OrangeKitten** [HuLu-TV1/developer-tools#5]
string str("dafei");
LOG_DEBUG(str) 会输出乱码
LOG_DEBUG(str.c_str()) 没问题

**Comment by shareworker** [comment]
@OrangeKitten 这是由于log模块内部实现导致，由于可变参数必须是 C-style 字符串或者 POD 类型，所以如果要使用此log模块，必须保证传入的log是C-style

**Comment by OrangeKitten** [comment]
嗯嗯 我发现也是这么回事，我试了跟你实现差不多的log库也会有这种问题。
