### ISSUE TITLE
使用setbuffer减少i/o操作是否会提高性能

### ISSUE THREAD

**Issue by OrangeKitten** [HuLu-TV1/developer-tools#6]
在输出到file的情况下，如果setbuffer一个本地缓存，将数据写入缓存中，在写满的情况下会自动清空缓冲写入到file中。或者起一个定时器几秒后自动调用fflush.

**Comment by shareworker** [comment]
@OrangeKitten 无论是写入到本地缓存还是起一个定时器自动调用fflush，都有丢log的风险，所以，相比较这点性能损耗，我还是比较喜欢实时fflush

**Comment by OrangeKitten** [comment]
可
