### ISSUE TITLE
ThreadPool的几点疑问

### ISSUE THREAD

**Issue by OrangeKitten** [HuLu-TV1/developer-tools#7]
1.通常do{}while(0)在宏定义使用的比较多，在ThreadPool的构造函数中使用do{}while(0)的目的是什么，好处是什么？
2.互斥锁在没有统一使用RAII 如主动调用unlock
3.在workTask对于操作 BusyNum 使用原子操作会不会更加节省性能？

**Comment by ZYY1015027303** [comment]
1.do while(0)可以在代码中实现代码分块，在一般工程代码中使用较多。本示例较为简单可以不考虑使用。
2.原子操作相对于互斥锁确实更加节省性能  后续考虑修改。。

**Comment by OrangeKitten** [comment]
manager.thread 可以根据 任务数量来减少workthread的个数，如果当前任务不密集，workthread数量减少了，等任务多起来了，由于workthread数量减少将会影响效率
